### ISSUE TITLE
doesnt start

### ISSUE THREAD

**Issue by pornoeule78** [OEFW-community/RT-890-SPI-Restore-CLI#1]
spi restore cli exe  doesnt start to install. not  on win 10 or 11

**Comment by Tunas1337** [comment]
Hi, it is a command line application. That means it does not install, nor show any graphical interface. You must open a command prompt in the current folder, and then run the application through it.

**Comment by pornoeule78** [comment]
ok i start, but the next step is not clear. is there a readme to use it?

**Comment by pornoeule78** [comment]
i have  it  now.  thanks

**Comment by pornoeule78** [comment]
it  works
